name: demo
channels:
  - defaults
dependencies:
  - pandas==0.23.4
  - pygraphviz==1.3
  - tensorflow
  - Keras
  - pytorch
  - torchvision
  - gym
  - pip
  - ipywidgets
  - pip:
    - keras-rl
    - qrcode
    - neptune-notebooks
    - jupyter_contrib_nbextensions
